name: Parallel Build and Push for ct-ng Configs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  discover-configs:
    runs-on: ubuntu-latest
    outputs:
      configs: ${{ steps.set-matrix.outputs.configs }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Discover ct-ng config files
        id: set-matrix
        run: |
          configs=$(find ./ctng_configs -type f -name "*.config" -exec basename {} \; | jq -R . | jq -s -c .)
          echo "Discovered configs: $configs"
          echo "::set-output name=configs::$configs"

  build-and-push:
    needs: discover-configs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: ${{ fromJson(needs.discover-configs.outputs.configs) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Ensure script is executable
        run: chmod +x ./Build_image.sh

      - name: Build and Push Docker image
        run: ./Build_image.sh -c "${{ matrix.config }}" -m push
