name: Parallel Build and Push for ct-ng Configs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  discover-configs:
    runs-on: ubuntu-latest
    outputs:
      configs: ${{ steps.set-matrix.outputs.configs }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Discover ct-ng config files
        id: set-matrix
        run: |
          cd docker_build
          configs=$(find ./ctng_configs -type f -name "*.config" -exec basename {} \; | jq -R . | jq -s -c .)
          echo "Discovered configs: $configs"
          echo "::set-output name=configs::$configs"

  build-and-push:
    needs: discover-configs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: ${{ fromJson(needs.discover-configs.outputs.configs) }}
      max-parallel: 1 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Free disk space
        run: |
          # https://github.com/jlumbroso/free-disk-space
          set -ex
          sudo rm -rf /usr/local/lib/android || true
          sudo rm -rf /usr/share/dotnet || true
          sudo rm -rf /opt/ghc || true
          sudo rm -rf /usr/local/.ghcup || true
          sudo docker image prune --all --force || true
          sudo rm -rf "$AGENT_TOOLSDIRECTORY" || true

      - name: Build and Push Docker image
        run: |
          cd docker_build
          chmod +x ./Build_image.sh
          ./Build_image.sh -c "${{ matrix.config }}"

      - name: Rename image
        run: |
          image_name=$(basename "${{ matrix.config }}" .config)
          docker tag local/ct-ng:${image_name} ${{ secrets.DOCKER_USERNAME }}/ct-ng:${image_name}

      - name: Push to Docker Hub
        run: |
          image_name=$(basename "${{ matrix.config }}" .config)
          docker push ${{ secrets.DOCKER_USERNAME }}/ct-ng:${image_name}